# Generated by Django 2.2.4 on 2019-08-25 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저 목록',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('username', models.CharField(max_length=30, verbose_name='이름')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('birth', models.DateField(verbose_name='생년월일')),
                ('language', models.CharField(choices=[('Korean', 'KR'), ('English', 'EN')], default='Korean', max_length=2, verbose_name='언어')),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='친구목록')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필 목록',
                'db_table': 'userProfile',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('assent', models.BooleanField(default=False, verbose_name='수락여부')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
                ('response_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_user', to=settings.AUTH_USER_MODEL, verbose_name='수락자')),
            ],
            options={
                'verbose_name': '친구 요청 Status',
                'verbose_name_plural': '친구 요청 Status 목록',
                'db_table': 'friend_request',
            },
        ),
    ]
