# Generated by Django 2.2.4 on 2019-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190826_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('KR', 'Korean'), ('EN', 'English')], default='KR', max_length=2, verbose_name='언어'),
        ),
    ]
