# Generated by Django 2.2.4 on 2019-08-26 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='휴일여부')),
                ('date', models.DateField(verbose_name='날짜')),
            ],
            options={
                'verbose_name': '휴일',
                'verbose_name_plural': '휴일 목록',
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('state', models.IntegerField(default=0, verbose_name='상태')),
                ('start_time', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('contents', models.CharField(blank=True, max_length=1000, null=True, verbose_name='내용')),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='참가자들')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrant', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정 목록',
                'db_table': 'schedule',
            },
        ),
    ]
